#!/usr/bin/python
# -*- coding: utf-8 -*-

import json
import sys

data = json.load(sys.stdin)
#data = data[0] # change this to find your string in the JSON
for d in data:
    sys.stdout.write(d['label'].encode('utf-8') + "\n")
