#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
from BeautifulSoup import BeautifulSoup

soup = BeautifulSoup("\n".join(sys.stdin.readlines()))

sect = soup.find("section", { "id" : "skd" })

trs = sect.findAll("tr")

try:
    for tr in trs:
        trp = tr.findAll("td")
        a = tr.findAll("a")
        r = ""
        for idx, trp_ in enumerate(trp):
            trpu = trp_.string
            if idx == 1: r += trpu.encode('utf-8')
            if idx == 2: r = trpu.replace(".", "")[0:-3].encode('utf-8') + "\t" + r
        print r
except IOError, e:
    pass
#    for a_ in a:
#        print a_['href'] + "\t",
#        print a_.string

### SOME TOTALLY WEIRD SHIT WITH THESE LISTS ... DUMB CODE!
### LIST HAD LENGTH 1 and a[0] or any other we tried returned index error??!?!?

#    b = [ a ]#[0]#['href']               
##
#    print type( a[0]['href'] )

#soup.find(text='Heading').findNext('ul').li
# <li>The data you want</li>
