#!/usr/bin/python

import sys
from BeautifulSoup import BeautifulSoup

data = "\n".join(sys.stdin.readlines())
soup = BeautifulSoup(data)

sect = soup.find("section", { "class" : "list-matches" })

trs = sect.findAllNext("tr")

for tr in trs:
    trp = tr.findAll("td")
    a = tr.findAll("a")
    for idx, trp_ in enumerate(trp):
        if idx == 2: print trp_.string.replace(".", "")[0:-3] + "\t",

    for a_ in a:
        print a_['href'] + "\t",
        print a_.string

### SOME TOTALLY WEIRD SHIT WITH THESE LISTS
### LIST HAD LENGTH 1 and a[0] or any other we tried returned index error??!?!?

#    b = [ a ]#[0]#['href']               
##
#    print type( a[0]['href'] )

#soup.find(text='Heading').findNext('ul').li
# <li>The data you want</li>
