#!/bin/bash

awk -F"\t" 'BEGIN {OFS="\t"} 
{  
gsub(/\./,"",$2)
if (CACHE[$1]) {
  $3 = CACHE[$1];
} else {
  ("./SKD-getgroupname \"" $1 "\"") |& getline $3;
  CACHE[$1] = $3;
}
print substr($2,0,length($2)-3), $3, $1; 
}'